/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Adminaddbook extends javax.swing.JFrame {

    /**
     * Creates new form Adminaddbook
     */
    Connection conn;
    ResultSet rs=null;
    PreparedStatement pst;
    public Adminaddbook() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnexit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtbookid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpub = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtedi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtpages = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnexit.setBackground(new java.awt.Color(0, 153, 153));
        btnexit.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 255, 255));
        btnexit.setText("X");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 50, 30));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book ID   ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        txtbookid.setBackground(new java.awt.Color(0, 102, 102));
        txtbookid.setForeground(new java.awt.Color(255, 255, 255));
        txtbookid.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 240, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name      ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        txtname.setBackground(new java.awt.Color(0, 102, 102));
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        txtname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 240, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Publisher ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        txtpub.setBackground(new java.awt.Color(0, 102, 102));
        txtpub.setForeground(new java.awt.Color(255, 255, 255));
        txtpub.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtpub, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 240, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Edition    ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        txtedi.setBackground(new java.awt.Color(0, 102, 102));
        txtedi.setForeground(new java.awt.Color(255, 255, 255));
        txtedi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 240, -1));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Pages       ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        txtpages.setBackground(new java.awt.Color(0, 102, 102));
        txtpages.setForeground(new java.awt.Color(255, 255, 255));
        txtpages.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtpages, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 240, -1));

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 90, 40));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 50, 30));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 390, 260));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("New Book");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 180, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 204, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 170, 20));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\imageedit_6_8540823161.png")); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        Adminaddbook ob=new Adminaddbook();

        ob.setVisible(false);
        ob.pack();
        ob.setLocationRelativeTo(null);//center
        ob.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        Adminhome b=new Adminhome();
        b.setVisible(true);
        b.pack();
        b.setLocationRelativeTo(null);//center
        b.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnexitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        conn=DB.ConnectDB();
        //insertuser("ff", email,   uname, pwd, repwd, gender, pic);

        Statement st;

        
        String Name=txtname.getText();
        String Bookid=txtbookid.getText();
        //bday=txtbday.getDate();
        String Pub=txtpub.getText();
        String Edi=txtedi.getText();
        String Pages = txtpages.getText();
        
      
        
        try {
            //JOptionPane.showMessageDialog(null, "Username is : " + txtuname.getText().trim().toString() + " Password is : " + txtpwd.getText().trim().toString(),"",JOptionPane.ERROR_MESSAGE);

            st = conn.createStatement();
             String sql="insert into neewbook(bookid,name,pub,edi,pages) values (?,?,?,?,?)";
                    pst=conn.prepareStatement(sql);
                    pst.setString(1,Bookid);
                    pst.setString(2, Name);
                    pst.setString(3, Pub);
                    pst.setString(4,Edi );
                    pst.setString(5,Pages );
                   
                    pst.execute();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
            

           

                //JOptionPane.showMessageDialog(null, " Welcome ","",JOptionPane.ERROR_MESSAGE);
                
                

                    
                    JOptionPane.showMessageDialog(Adminaddbook.this,"book added successfully!");

                
               

               

                   
                    //pst.executeUpdate(sql);

                    //"book ID already exit in your issed books!","",JOptionPane.ERROR_MESSAGE

                
                /*try{

                    String sql="insert into userdate (bookid,uname,date) values (?,?,?) ";
                    pst=conn.prepareStatement(sql);
                    pst.setString(1,Bookid );
                    pst.setString(2,Uname );
                    pst.setDate(3, datee);
                    pst.execute();
                    // pst.executeUpdate(sql);

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                    System.out.println("bbbbbbbbbbb"+e);
                }*/
           
        
        // pst.executeUpdate(sql);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setState(login.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminaddbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminaddbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminaddbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminaddbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminaddbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtedi;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpages;
    private javax.swing.JTextField txtpub;
    // End of variables declaration//GEN-END:variables
}
