/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Newbook extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    
    
    
    String Name;
    String Bookid;
    //Date Bday;
    String Pub;
    
    /**
     * Creates new form Newbook
     */
    public Newbook() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpwd = new javax.swing.JTextField();
        txtbookid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtpub = new javax.swing.JTextField();
        txtedi = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtpages = new javax.swing.JTextField();
        txtuname = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txts = new javax.swing.JTextField();
        btnexit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtdate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 430));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 430));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book ID   ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name      ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Publisher ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Edition    ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        txtpwd.setBackground(new java.awt.Color(0, 102, 102));
        txtpwd.setForeground(new java.awt.Color(255, 255, 255));
        txtpwd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 240, -1));

        txtbookid.setBackground(new java.awt.Color(0, 102, 102));
        txtbookid.setForeground(new java.awt.Color(255, 255, 255));
        txtbookid.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 240, -1));

        txtname.setBackground(new java.awt.Color(0, 102, 102));
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        txtname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 240, -1));

        txtpub.setBackground(new java.awt.Color(0, 102, 102));
        txtpub.setForeground(new java.awt.Color(255, 255, 255));
        txtpub.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtpub, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 240, -1));

        txtedi.setBackground(new java.awt.Color(0, 102, 102));
        txtedi.setForeground(new java.awt.Color(255, 255, 255));
        txtedi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 240, -1));

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 90, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\if_note_1296370(1).png")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Pages       ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("User name");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        txtpages.setBackground(new java.awt.Color(0, 102, 102));
        txtpages.setForeground(new java.awt.Color(255, 255, 255));
        txtpages.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtpages, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 240, -1));

        txtuname.setBackground(new java.awt.Color(0, 102, 102));
        txtuname.setForeground(new java.awt.Color(255, 255, 255));
        txtuname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 240, -1));

        jButton6.setBackground(new java.awt.Color(0, 51, 51));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\if_search_173095.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 30, 30));

        jButton7.setBackground(new java.awt.Color(0, 51, 51));
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\if_search_173095.png")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 30, 30));

        jLabel16.setForeground(new java.awt.Color(255, 102, 204));
        jLabel16.setText("Search book id by name or publisher.....");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        jPanel1.add(txts, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 320, -1));

        btnexit.setBackground(new java.awt.Color(0, 153, 153));
        btnexit.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 255, 255));
        btnexit.setText("X");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 50, 30));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 50, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\imageedit_14_6099540669.png")); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, 180));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\brainstorm(2).png")); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 100, 180));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\strategy.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, 150));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\creativity.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, 150));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\rising.png")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, 150));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\education.png")); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, 150));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\brainstorm(4).png")); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, 160));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\brainstorm(5).png")); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, 150));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\brainstorming.png")); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, 150));

        jPanel3.setBackground(new java.awt.Color(79, 151, 126));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\if_contacts_1055082(1).png")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Book");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(104, 104, 104))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 240, 40));

        txtdate.setForeground(new java.awt.Color(255, 204, 255));
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 120, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date of issue : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\imageedit_6_8540823161.png")); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 442));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        Newbook ob=new Newbook();
        
        ob.setVisible(false);
        ob.pack();
        ob.setLocationRelativeTo(null);//center
        ob.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        Userhome b=new Userhome();
        b.setVisible(true);
        b.pack();
        b.setLocationRelativeTo(null);//center
        b.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnexitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setState(login.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        conn=DB.ConnectDB();
        //insertuser("ff", email,   uname, pwd, repwd, gender, pic);
        
        Statement st;
        
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            Date date=new Date();
             String Name=txtname.getText();
             Bookid=txtbookid.getText();
             //bday=txtbday.getDate();
             Pub=txtpub.getText();
             String Edi=txtedi.getText();
        String Pages = txtpages.getText();
             String Uname=txtuname.getText();
             String Pwd=txtpwd.getText();
             //String t=sdf.format(date).toString();
             //Date s=sdf.parse(date);
             // create a java calendar instance
Calendar calendar = Calendar.getInstance();

// get a java date (java.util.Date) from the Calendar instance.
// this java date will represent the current date, or "now".
java.util.Date currentDate = calendar.getTime();

// now, create a java.sql.Date from the java.util.Date
java.sql.Date datee = new java.sql.Date(currentDate.getTime());
             //String t = sdf.format(txtdate.getd).toString(); 
             //;
             //=sdf.txtdate;
             //String f=txtdate.gett
             //JOptionPane.showMessageDialog(null, t);
            //String name=txtname.getText();
            
           
        
           
       
      
        try
        {
            //JOptionPane.showMessageDialog(null, "Username is : " + txtuname.getText().trim().toString() + " Password is : " + txtpwd.getText().trim().toString(),"",JOptionPane.ERROR_MESSAGE);
        
        st = conn.createStatement();
        ResultSet rs = st.executeQuery("Select bookid,name,pub,edi from neewbook where bookid = '"+txtbookid.getText()+"' and name = '"+txtname.getText()+"'and pub = '"+txtpub.getText()+"'and edi = '"+txtedi.getText()+"'");


        if(rs.next())
        {

            //JOptionPane.showMessageDialog(null, " Welcome ","",JOptionPane.ERROR_MESSAGE);
            ResultSet rs1 = st.executeQuery("Select uname,pwd from register where uname = '"+txtuname.getText()+"' and pwd = '"+txtpwd.getText()+"'");
            if(rs1.next())
            {
                
                txtdate.setText(sdf.format(date));
                JOptionPane.showMessageDialog(Newbook.this,"book added successfully!");
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Your Username or Password is incorrect","",JOptionPane.ERROR_MESSAGE);
            }
            
            try{
            
            
            String sql="insert into issuedbooks(bookid,name,pub,edi,pages,uname,pwd,date) values (?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1,Bookid);
            pst.setString(2, Name);
            pst.setString(3, Pub);
            pst.setString(4,Edi );
            pst.setString(5,Pages );
            pst.setString(6,Uname );
            pst.setString(7, Pwd);
            pst.setDate(8, datee);
            pst.execute();
           //pst.executeUpdate(sql);
            
            //"book ID already exit in your issed books!","",JOptionPane.ERROR_MESSAGE
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e );
                System.out.println("aaaaaaaaaa"+e);
        }
         /*try{
            
            
            String sql="insert into userdate (bookid,uname,date) values (?,?,?) ";
            pst=conn.prepareStatement(sql);
            pst.setString(1,Bookid );
            pst.setString(2,Uname );
            pst.setDate(3, datee);
            pst.execute();
           // pst.executeUpdate(sql);
            
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
             System.out.println("bbbbbbbbbbb"+e);
        }*/
        }

        else
        {
            JOptionPane.showMessageDialog(null, "Wrong details!","",JOptionPane.ERROR_MESSAGE);

        }
        
        
        }catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, e); 
        }
           // pst.executeUpdate(sql);
            
          
            
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        conn=DB.ConnectDB();
        String sql="select * from neewbook where bookid=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,txtbookid.getText());
            rs=pst.executeQuery();
            if(rs.next())
            {
                String Name=rs.getString("name");
                txtname.setText(Name);
                String Pub=rs.getString("pub");
                txtpub.setText(Pub);
                String Edi=rs.getString("edi");
                txtedi.setText(Edi);
                String Pages=rs.getString("pages");
                txtpages.setText(Pages);
                 
                Userlogin a=new Userlogin();
                String x=a.getuser();
                txtuname.setText(x);
                 
                
                
                
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        try{
           Sbyname s=new Sbyname();
           String Name=txts.getText();
           s.tableload(Name);
           s.setVisible(true);
        s.pack();
        s.setLocationRelativeTo(null);//center
        //s.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //this.dispose();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed
int xx,xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
         int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_formMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JLabel txtdate;
    private javax.swing.JTextField txtedi;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpages;
    private javax.swing.JTextField txtpub;
    private javax.swing.JTextField txtpwd;
    private javax.swing.JTextField txts;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
