/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
//import java.util.Date;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
//import sun.util.calendar.BaseCalendar.Date;


/**
 *
 * @author User
 */
public class Register extends javax.swing.JFrame {
    String gender;
    String filename=null;
    Blob Pic;
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    private Object PicUtil;
    String Name;
    String Email;
    //Date Bday;
    String Uname;
    String Pwd;
    String Repwd;
    

    
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);//center
    
    }
 
           
            
           

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnupload = new javax.swing.JButton();
        jLabelphoto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbtnfemale = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbtnmale = new javax.swing.JRadioButton();
        txtname = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtuname = new javax.swing.JTextField();
        txtbday = new org.jdesktop.swingx.JXDatePicker();
        txtpwd = new javax.swing.JPasswordField();
        txtrepwd = new javax.swing.JPasswordField();
        btnregister = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jLabel12.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Footlight MT Light", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Full Name          :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-mail               :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Name         :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BirthDate           :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password            :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Re-type Password:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        btnupload.setBackground(new java.awt.Color(0, 102, 102));
        btnupload.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnupload.setForeground(new java.awt.Color(255, 255, 255));
        btnupload.setText("Upload");
        btnupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadActionPerformed(evt);
            }
        });
        jPanel1.add(btnupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 110, -1));

        jLabelphoto.setForeground(new java.awt.Color(255, 0, 102));
        jLabelphoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabelphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 110, 117));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender               :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 107, -1));

        rbtnfemale.setBackground(new java.awt.Color(0, 51, 51));
        rbtnfemale.setForeground(new java.awt.Color(255, 255, 255));
        rbtnfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnfemaleActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Female");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("male");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        rbtnmale.setBackground(new java.awt.Color(0, 51, 51));
        rbtnmale.setForeground(new java.awt.Color(255, 255, 255));
        rbtnmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnmaleActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        txtname.setBackground(new java.awt.Color(153, 255, 255));
        txtname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 219, -1));

        txtemail.setBackground(new java.awt.Color(153, 255, 255));
        txtemail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 219, -1));

        txtuname.setBackground(new java.awt.Color(153, 255, 255));
        txtuname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 219, -1));

        txtbday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbdayActionPerformed(evt);
            }
        });
        jPanel1.add(txtbday, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        txtpwd.setBackground(new java.awt.Color(153, 255, 255));
        txtpwd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpwdActionPerformed(evt);
            }
        });
        jPanel1.add(txtpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 219, -1));

        txtrepwd.setBackground(new java.awt.Color(153, 255, 255));
        txtrepwd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtrepwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 219, -1));

        btnregister.setBackground(new java.awt.Color(0, 153, 153));
        btnregister.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnregister.setForeground(new java.awt.Color(255, 255, 255));
        btnregister.setText("Register");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 100, 40));

        btnback.setBackground(new java.awt.Color(255, 102, 102));
        btnback.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 100, 40));

        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 220, -1));

        l3.setForeground(new java.awt.Color(255, 51, 102));
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 220, 20));

        l8.setForeground(new java.awt.Color(204, 0, 102));
        jPanel1.add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 90, 80));

        btnexit.setBackground(new java.awt.Color(0, 153, 153));
        btnexit.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 255, 255));
        btnexit.setText("X");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 50, 30));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 50, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\ezgif.com-gif-maker(1).gif")); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTER FORM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 0, 18), java.awt.Color.lightGray)); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 390, 470));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\imageedit_3_4617575574.png")); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 420, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadActionPerformed
        // TODO add your handling code here:
        JFileChooser ch=new JFileChooser();
        ch.showOpenDialog(null);
        File f=ch.getSelectedFile();
        filename=f.getAbsolutePath();
        ImageIcon imageIcon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(jLabelphoto.getWidth(), jLabelphoto.getHeight(), Image.SCALE_SMOOTH));
        jLabelphoto.setIcon(imageIcon);
        try{
            File image=new File(filename);
            FileInputStream fis=new FileInputStream(image);
            //ByteArrayOutputStream baos=new ByteArrayOutputStream();
            //byte[] b=new byte[1024];
            //for(int readNum;(readNum=fis.read(b))!=-1;){
                //baos.write(b, 0, readNum);
            //}
            //Pic=baos.toByteArray();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnuploadActionPerformed

    private void rbtnfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnfemaleActionPerformed
        // TODO add your handling code here:
        
        
            gender="female";
       
    }//GEN-LAST:event_rbtnfemaleActionPerformed

    private void rbtnmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnmaleActionPerformed
        // TODO add your handling code here:
        gender="male";
    }//GEN-LAST:event_rbtnmaleActionPerformed

    private void txtpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpwdActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        Userlogin ob=new Userlogin();
        ob.setVisible(true);
        ob.pack();
        ob.setLocationRelativeTo(null);//center
        ob.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:
        
        conn=DB.ConnectDB();
        //insertuser("ff", email,   uname, pwd, repwd, gender, pic);
        
       
        try{
            
             String Name=txtname.getText();
             Email=txtemail.getText();
             //bday=txtbday.getDate();
           Uname=txtuname.getText();
            Pwd=txtpwd.getText();
             Repwd=txtrepwd.getText();
            //String name=txtname.getText();
            
            File image=new File(filename);
            FileInputStream fis=new FileInputStream(image);
            SimpleDateFormat date =new SimpleDateFormat("yyyy-mm-dd");
           String Bday = date.format(txtbday.getDate()).toString();
        
            String sql="insert into register(name,email,bday,uname,pwd,repwd,gender,pic) values (?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            
            
               pst.setString(1,Name); 
            
            
            pst.setString(2, Email);
            pst.setString(3, Bday);
            pst.setString(4,Uname );
            pst.setString(5,Pwd );
            pst.setString(6,Repwd );
            pst.setString(7, gender);
            pst.setBinaryStream(8, (InputStream)fis,(int)image.length());
            pst.execute();
           // pst.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(Register.this,"Librarian added successfully!");
            JOptionPane.showMessageDialog(Register.this,"user name:"+Uname+"\n"+"password :"+Pwd);
        }catch(Exception e){
           
                JOptionPane.showMessageDialog(null, "Fields can't be null!");
           
            
            
        }
    }//GEN-LAST:event_btnregisterActionPerformed

    private void txtbdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbdayActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtbdayActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setState(login.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed
int xx,xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_formMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnregister;
    private javax.swing.JButton btnupload;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelphoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l8;
    private javax.swing.JRadioButton rbtnfemale;
    private javax.swing.JRadioButton rbtnmale;
    private org.jdesktop.swingx.JXDatePicker txtbday;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpwd;
    private javax.swing.JPasswordField txtrepwd;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
